# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [1]:
# Please consult the lectures
import numpy as np
v = np.array([1, 2, 3])
print(v.shape)  # Output: (3,)
print("A vector is a 1-dimensional (1D) array")

(3,)
A vector is a 1-dimensional (1D) array


In [2]:
m = np.array([[1, 2, 3], [4, 5, 6]])
print(m.shape)  # Output: (2, 3)
print("A matrix is a 2-dimensional (2D) array")

(2, 3)
A matrix is a 2-dimensional (2D) array


**2. How to import `NumPy` library?** 

In [3]:
# To avoid overwriting the output, please code here 
import numpy as np

**3. Convert the given Python list into NumPy array and check its data type**

In [4]:
list_1 = [1,2,3,4,5]

In [35]:
# To avoid overwriting the output, please code here 
array_1 = np.array(list_1)
print("Data Type:", array_1.dtype)
print((array_1, type(array_1)))

Data Type: int32
(array([1, 2, 3, 4, 5]), <class 'numpy.ndarray'>)


(array([1, 2, 3, 4, 5]), numpy.ndarray)

**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [36]:
# To avoid overwriting the output, please code here 
arr = np.arange(6)
print(repr(arr))

array([0, 1, 2, 3, 4, 5])


array([0, 1, 2, 3, 4, 5])

**5. Generate an `array of "5" zeros` **

In [37]:
# To avoid overwriting the output, please code here 
zeros_array = np.zeros(5)
print(repr(zeros_array))

array([0., 0., 0., 0., 0.])


array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [38]:
# To avoid overwriting the output, please code here 
matrix = np.zeros((3, 4))
print(repr(matrix))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])


array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [18]:
# To avoid overwriting the output, please code here 
ones_array = np.ones(5)
print(ones_array)

[1. 1. 1. 1. 1.]


[ 1.  1.  1.  1.  1.]


**8. Generate an array of "5" tens.**

In [19]:
# To avoid overwriting the output, please code here 
tens_array = np.ones(5) * 10
print(tens_array)

[10. 10. 10. 10. 10.]


array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [39]:
# To avoid overwriting the output, please code here 
even_array = np.arange(52, 100, 2)
print(repr(even_array))

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])


array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [22]:
# To avoid overwriting the output, please code here 
arr = np.linspace(0, 1, 10)
print("Array:", arr)
step = arr[1] - arr[0]
print("Step size:", step)

Array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Step size: 0.1111111111111111


(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [23]:
# To avoid overwriting the output, please code here 
vector = np.arange(25)
print("Vector:\n", vector)

Vector:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
# To avoid overwriting the output, please code here 
matrix = vector.reshape(5, 5)
print("\n2D Matrix:\n", matrix)


2D Matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# To avoid overwriting the output, please code here 
vector.shape = (5, 5)
print("\nMatrix using shape attribute:\n", vector)


Matrix using shape attribute:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [27]:
# To avoid overwriting the output, please code here 
arr = np.arange(0.1, 2.6, 0.1).reshape(5, 5)
print(repr(arr))

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])


array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [28]:
# To avoid overwriting the output, please code here 
arr = np.linspace(0, 24, 25, dtype=int).reshape(5, 5)
print(repr(arr))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [31]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.  
# linspace() take 3rd argument as no of point we want.

In [29]:
#arrange() Doesnt include stop.
#linspace() Includes Stop

**15. How to generate a single random integer number using NumPy built-in function?**

In [31]:
# To avoid overwriting the output, please code here 
random_int = np.random.randint(low=0, high=10)  # generates integer from 0 to 9
print(random_int)

1


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [32]:
# To avoid overwriting the output, please code here 
np.random.seed(0)  # Optional: for reproducibility
matrix = np.random.rand(7, 5)
print(matrix)

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [33]:
# To avoid overwriting the output, please code here 
matrix = 5 * np.identity(5)
print(repr(matrix))

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])


array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 